//
//  File.swift
//
//
//  Created by Oliver Drobnik on 01.05.24.
//

import Foundation

public struct File: Codable, Sendable {
    /// Unique identifier for the assistant.
    public let id: String

    /// Type of object, consistently a "file".
    public let object: String

    /// The timestamp when the assistant was created.
    public let createdAt: Date

    /// The size of the file
    public let bytes: Int

    /// The filename
    public let filename: String

    /// The purpose of the file
    public let purpose: Purpose

    public enum Purpose: String, Codable, Sendable {
        /// Files for fine-tuning
        case finetune = "fine-tune"

        /// Files uploaded for use with Assistants are not permitted to be downloaded
        case assistants

        /// For Batch API the file format must be `.jsonl`
        case batch

        /// For user files
        case userData = "user_data"

        /// output generated by code interpreter. Supported formats: gif, jpeg, jpg, png, webp
        case assistantsOutput = "assistants_output"

        ///  Assistants image file inputs
        case vision
    }

    /*
     "invalidRequest("\'fine-tuned\' is not one of [\'fine-tune\', \'assistants\', \'batch\', \'user_data\', \'responses\', \'vision\'] - \'purpose\'")"

      */

    public init(id: String, object: String, createdAt: Date, bytes: Int, filename: String, purpose: Purpose) {
        self.id = id
        self.object = object
        self.createdAt = createdAt
        self.bytes = bytes
        self.filename = filename
        self.purpose = purpose
    }
}
