//
//  ChatCompletionResponse.swift
//  OpenAI
//
//  Created by Oliver Drobnik on 19.04.24.
//

import Foundation

/// Represents a completion response from the OpenAI API.
public struct ChatCompletionResponse: Codable, Sendable {
	/// A choice of message generated by the API.
	public struct Choice: Codable, Sendable {
		/// The message generated by the API.
		public let message: ChatMessage

		/// The reason why the completion was finished, such as "max_tokens" or "stop".
		public let finishReason: FinishReason?

		/// The index of the choice, starting from 0.
		public let index: Int

		public init(message: ChatMessage, finishReason: FinishReason?, index: Int) {
			self.message = message
			self.finishReason = finishReason
			self.index = index
		}
	}

	/// The ID of the completion request. Google doesn't set one
	public let id: String?

	/// The type of object, which is always "chat.completion".
	public let object: String

	/// The Unix timestamp when the completion request was created.
	public let created: Date

	/// The ID of the model used to generate the completion.
	public let model: String

	/// The usage statistics for the completion request.
	public var usage: Usage?

	/// The list of choices generated by the API.
	public var choices: [Choice]

	public init(id: String, object: String, created: Date, model: String, usage: Usage?, choices: [Choice]) {
		self.id = id
		self.object = object
		self.created = created
		self.model = model
		self.usage = usage
		self.choices = choices
	}
}

public enum FinishReason: String, Codable, Sendable {
	case stop
	case limit
	case functionCall = "function_call"
	case contentFilter = "content_filter"
	case toolCalls = "tool_calls"
}
