//
//  ChatMessage.swift
//  OpenAI
//
//  Created by Oliver Drobnik on 14.06.23.
//

import Foundation
import SwiftMCP

/// Represents a message in a conversation.
/// - Note: requires conversion to and from snake case, and iso date parsing strategy
public struct ChatMessage: Codable, Sendable
{
	/// The role of the author of this message.
	public let role: Role

	/// Responses API assistant message phase, when present.
	public var phase: Response.Phase?
	
	public var toolCallID: String?
	
	public enum Content: Codable, Sendable {
		case text(String)
		case parts([ContentPart])

		public init(from decoder: Decoder) throws {
			let container = try decoder.singleValueContainer()
			if let string = try? container.decode(String.self) {
				self = .text(string)
			} else {
				let parts = try container.decode([ContentPart].self)
				self = .parts(parts)
			}
		}

		public func encode(to encoder: Encoder) throws {
			var container = encoder.singleValueContainer()
			switch self {
				case .text(let string):
					try container.encode(string)
				case .parts(let parts):
					try container.encode(parts)
			}
		}
	}

	/// The contents of the message. It's optional, because if there's a function call response, then content will be null
	public var content: Content?
	
	/// The refusal message generated by the model.
	public var refusal: String?
	
	/// Specific to DeepSeek-r1
	public var reasoningContent: String?
	
	/// The name of the author of this message. May contain a-z, A-Z, 0-9, and underscores, with a maximum length of 64 characters.
	public let name: String?
	
	/// The function call if it exists in the message.
	public let functionCall: FunctionCall?

	/// The tool calls if they exist in the message
	public var toolCalls: [ToolCall]?

	/// Initializes a new `Message` instance with the specified parameters.
	public init(role: Role,
				 content: Content? = nil,
				 phase: Response.Phase? = nil,
				 name: String? = nil,
				 functionCall: FunctionCall? = nil,
				 toolCallID: String? = nil,
				 toolCalls: [ToolCall]? = nil)
	{
		self.role = role
		self.content = content
		self.phase = phase
		self.name = name
		self.functionCall = functionCall
		self.toolCallID = toolCallID
		self.toolCalls = toolCalls
	}
	
	enum CodingKeys: String, CodingKey
	{
		case role, content, phase, refusal, reasoningContent, name, functionCall, toolCalls, toolCallID
	}
	
	public init(from decoder: Decoder) throws
	{
		let container = try decoder.container(keyedBy: CodingKeys.self)
		role = try container.decode(Role.self, forKey: .role)
		content = try container.decodeIfPresent(Content.self, forKey: .content)
		phase = try container.decodeIfPresent(Response.Phase.self, forKey: .phase)
		refusal = try container.decodeIfPresent(String.self, forKey: .refusal)
		reasoningContent = try container.decodeIfPresent(String.self, forKey: .reasoningContent)
		name = try container.decodeIfPresent(String.self, forKey: .name)
		functionCall = try container.decodeIfPresent(FunctionCall.self, forKey: .functionCall)
		toolCalls = try container.decodeIfPresent(Array<ToolCall>.self, forKey: .toolCalls)
		toolCallID = try container.decodeIfPresent(String.self, forKey: .toolCallID)
	}

	public func encode(to encoder: Encoder) throws
	{
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(role, forKey: .role)
		try container.encodeIfPresent(content, forKey: .content)
		try container.encodeIfPresent(phase, forKey: .phase)
		try container.encodeIfPresent(refusal, forKey: .refusal)
		try container.encodeIfPresent(reasoningContent, forKey: .reasoningContent)
		try container.encodeIfPresent(name, forKey: .name)
		try container.encodeIfPresent(functionCall, forKey: .functionCall)
		try container.encodeIfPresent(toolCalls, forKey: .toolCalls)
		try container.encodeIfPresent(toolCallID, forKey: .toolCallID)
	}

}

extension ChatMessage: CustomDebugStringConvertible
{
	public var debugDescription: String
	{
		var tmpStr = ""
		
		switch role
		{
			case .assistant:
				tmpStr += "Assistant"
				
			case .function:
				tmpStr += "Function"
				
				if let name = name
				{
					tmpStr += " `" + name + "`"
				}
				
				tmpStr += " result"

			case .tool:
				tmpStr += "Tool"
				
				if let name = name
				{
					tmpStr += " `" + name + "`"
				}
				
				tmpStr += " result"
				
			case .system:
				tmpStr += "System"
				
			case .user:
				
				if let name = name
				{
					tmpStr += name
				}
				else
				{
					tmpStr += "User"
				}
			case .developer:
				tmpStr += "Developer"
		}
		
		tmpStr += ":"
		
		if let content = content
		{
			switch content {
				case .text(let string):
					tmpStr += "\n\"" + string + "\""
				case .parts(let parts):
					let text = parts.compactMap { $0.text }.joined(separator: " \n")
					if !text.isEmpty {
						tmpStr += "\n\"" + text + "\""
					}
		}
		}
		
		tmpStr += "\n"
		
		if let call = functionCall
		{
			tmpStr += " -> calling `" + call.name + "("
			
			if let data = call.arguments.data(using: .utf8),
			   let arguments = try? JSONSerialization.jsonObject(with: data, options: []) as? [String: Any]
			{
				var cleanedDict = [String: Any]()

				for (key, value) in arguments {
					if let nsArray = value as? NSArray {
						cleanedDict[key] = Array(nsArray)
					} else {
						cleanedDict[key] = value
					}
				}
				
				var paramStr = ""
				
				for key in cleanedDict.keys.sorted()
				{
					if !paramStr.isEmpty
					{
						paramStr += ", "
					}
					
					paramStr += key + ": "
					
					let value = cleanedDict[key]
					
					if let string = value as? String
					{
						paramStr += "\"\(string)\""
					}
					else
					{
						paramStr += "\(value.debugDescription)"
					}
				}
				
				tmpStr += paramStr.replacingOccurrences(of: "\n", with: "\\n")
			}
			
			tmpStr += ")`\n"
		}
		
		return tmpStr
	}
}

public extension ChatMessage {
	var textContent: String? {
		guard let content = content else { return nil }
		if case .text(let string) = content {
			return string
		}
		return nil
	}

	var contentParts: [ContentPart]? {
		guard let content = content else { return nil }
		if case .parts(let parts) = content {
			return parts
		}
		return nil
	}
}

	public extension ChatMessage {
		struct ContentPart: Codable, Sendable {
			public enum PartType: Codable, Sendable {
				case text
				case imageURL
				case inputAudio
				case file

			public init(from decoder: Decoder) throws {
				let container = try decoder.singleValueContainer()
				let raw = try container.decode(String.self)
				switch raw {
					case "text", "input_text":
						self = .text
					case "image_url":
						self = .imageURL
					case "input_audio":
						self = .inputAudio
					case "file":
						self = .file
					default:
						throw DecodingError.dataCorruptedError(in: container, debugDescription: "Unknown content part type \(raw)")
				}
			}

			public func encode(to encoder: Encoder) throws {
				var container = encoder.singleValueContainer()
				try container.encode(encodedValue)
			}

			var encodedValue: String {
				switch self {
					case .text:
						return "text"
					case .imageURL:
						return "image_url"
					case .inputAudio:
						return "input_audio"
					case .file:
						return "file"
				}
			}
		}

		public struct ImageURL: Codable, Sendable {
			public var url: String
			public var mimeType: String?

			public init(url: String, mimeType: String? = nil) {
				self.url = url
				self.mimeType = mimeType
			}

			private enum CodingKeys: String, CodingKey {
				case url
				case mimeType = "mime_type"
			}
		}
		
		public struct InputAudio: Codable, Sendable {
			public var data: String
			public var format: String

			public init(data: String, format: String) {
				self.data = data
				self.format = format
			}
		}

		public struct FilePart: Codable, Sendable {
			public var fileID: String?
			public var filename: String?
			public var fileData: String?

			public init(fileID: String? = nil, filename: String? = nil, fileData: String? = nil) {
				self.fileID = fileID
				self.filename = filename
				self.fileData = fileData
			}
		}

			public let type: PartType
			public var text: String?
			public var imageURL: ImageURL?
			public var inputAudio: InputAudio?
			public var file: FilePart?

			public init(text: String) {
				self.type = .text
				self.text = text
				self.imageURL = nil
				self.inputAudio = nil
				self.file = nil
			}

			public init(imageURL: String, mimeType: String? = nil) {
				self.type = .imageURL
				self.text = nil
				self.imageURL = ImageURL(url: imageURL, mimeType: mimeType)
				self.inputAudio = nil
				self.file = nil
			}

			public init(inputAudioData: String, format: String) {
				self.type = .inputAudio
				self.text = nil
				self.imageURL = nil
				self.inputAudio = InputAudio(data: inputAudioData, format: format)
				self.file = nil
			}

			public init(fileID: String? = nil, filename: String? = nil, fileData: String? = nil) {
				self.type = .file
				self.text = nil
				self.imageURL = nil
				self.inputAudio = nil
				self.file = FilePart(fileID: fileID, filename: filename, fileData: fileData)
			}

			private enum CodingKeys: String, CodingKey {
				case type
				case text
				case imageURL = "image_url"
				case inputAudio = "input_audio"
				case file
			}

			public init(from decoder: Decoder) throws {
				let container = try decoder.container(keyedBy: CodingKeys.self)
				type = try container.decode(PartType.self, forKey: .type)
				switch type {
					case .text:
						text = try container.decodeIfPresent(String.self, forKey: .text)
						imageURL = nil
						inputAudio = nil
						file = nil
					case .imageURL:
						text = nil
						imageURL = try container.decodeIfPresent(ImageURL.self, forKey: .imageURL)
						inputAudio = nil
						file = nil
					case .inputAudio:
						text = nil
						imageURL = nil
						inputAudio = try container.decodeIfPresent(InputAudio.self, forKey: .inputAudio)
						file = nil
					case .file:
						text = nil
						imageURL = nil
						inputAudio = nil
						file = try container.decodeIfPresent(FilePart.self, forKey: .file)
				}
			}

			public func encode(to encoder: Encoder) throws {
				var container = encoder.container(keyedBy: CodingKeys.self)
				try container.encode(encodedType, forKey: .type)
				switch type {
					case .text:
						try container.encode(text, forKey: .text)
					case .imageURL:
						if let imageURL {
							try container.encode(imageURL, forKey: .imageURL)
						}
					case .inputAudio:
						try container.encode(inputAudio, forKey: .inputAudio)
					case .file:
						try container.encode(file, forKey: .file)
				}
			}

		public var textValue: String? {
			if case .text = type {
				return text
			}
			return nil
		}

		var encodedType: String {
			switch type {
				case .text:
					return "text"
				case .imageURL:
					return "image_url"
				case .inputAudio:
					return "input_audio"
				case .file:
					return "file"
			}
		}
	}

}

public extension ChatMessage.ContentPart {
	static func textParts(from parts: [ChatMessage.ContentPart]) -> [String] {
		parts.compactMap { $0.textValue }
	}

	static func joinedText(from parts: [ChatMessage.ContentPart]) -> String? {
		let texts = textParts(from: parts)
		guard !texts.isEmpty else { return nil }
		return texts.joined(separator: "\n")
	}

	static func imageDataPart(mimeType: String, data: Data) -> ChatMessage.ContentPart {
		let base64 = data.base64EncodedString()
		let dataURL = "data:\(mimeType);base64,\(base64)"
		return ChatMessage.ContentPart(imageURL: dataURL)
	}

	func decodedImageData() -> (mimeType: String, data: Data)? {
		guard type == .imageURL,
			  let urlString = imageURL?.url else {
			return nil
		}
		return Self.decodeDataURL(urlString)
	}

	private static func decodeDataURL(_ string: String) -> (mimeType: String, data: Data)? {
		guard string.starts(with: "data:"),
			  let commaIndex = string.firstIndex(of: ",") else {
			return nil
		}
		let meta = string[string.startIndex..<commaIndex]
		let dataPortion = string[string.index(after: commaIndex)...]
		let mimeType: String
		if let typeRange = meta.range(of: ":") {
			let typeString = meta[typeRange.upperBound...]
			if let semiRange = typeString.firstIndex(of: ";") {
				mimeType = String(typeString[..<semiRange])
			} else {
				mimeType = String(typeString)
			}
		} else {
			mimeType = "application/octet-stream"
		}
		guard let data = Data(base64Encoded: String(dataPortion)) else {
			return nil
		}
		return (mimeType, data)
	}
}

public struct FunctionCall: Codable, Sendable
{
	public var name: String
	public var arguments: String
	
	public init(name: String, arguments: String)
	{
		self.name = name
		self.arguments = arguments
	}
	
	public func argumentsDictionary() throws -> [String: JSONValue]
	{
		guard !arguments.isEmpty,
			  let data = arguments.data(using: .utf8) else
		{
			return [:]
		}
		
		let jsonObject = try JSONSerialization.jsonObject(with: data, options: [])
		
		if let dict = jsonObject as? [String: Any]
		{
			return .init(jsonObject: dict)
		}
		else if let array =  jsonObject as? [[String: Any]]
		{
			var argumentsDict: [String: JSONValue] = [:]
			
			for item in array
			{
				if let name = item["name"] as? String,
					let value = item["value"]
				{
					argumentsDict[name] = .init(jsonObject: value)
				}
			}
			
			return argumentsDict
		}
		
		return [:]
	}
	
	public var description: String
	{
		var str = "\(name)("
		
		if let arguments = try? argumentsDictionary()
		{
			let argStrs = arguments.keys.sorted().map { key in
				
				var str = key + ":"
				
				let value = arguments[key]!
				if let string = value.stringValue {
					let escaped = string.replacingOccurrences(of: "\"", with: "\\\"")
					str += "\"\(escaped)\""
				} else {
					str += value.description
				}
				
				return str
			}
			
			str += argStrs.joined(separator: " ")
		}
		
		str += ")"
		
		return str
	}
}

public struct ToolCall: Codable, Sendable
{
	public var id: String
	public var type: String
	public var function: FunctionCall?
	
	public init(id: String, type: String, function: FunctionCall?)
	{
		self.id = id
		self.type = type
		self.function = function
	}
}

public struct FunctionCallResult: Codable
{
	public let name: String
	public let arguments: String
	public var result: String?
}
