//
//  ResponseOutput.swift
//  SwiftAgents
//
//  Created by Oliver Drobnik on 24.04.25.
//

import Foundation

/// Represents an output item from the model.
public enum ResponseOutput: Codable, Sendable {
    /// An output message from the model.
    case message(OutputMessage)

    /// The results of a file search tool call.
    case fileSearchCall(FileSearchToolCall)

    /// A tool call to run a function.
    case functionCall(FunctionToolCall)

    /// The results of a web search tool call.
    case webSearchCall(WebSearchToolCall)

    /// A tool call to a computer use tool.
    case computerCall(ComputerToolCall)

    /// A description of the chain of thought used by a reasoning model.
    case reasoning(Reasoning)

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let type = try container.decode(String.self, forKey: .type)

        switch type {
        case "message":
            self = .message(try OutputMessage(from: decoder))
        case "file_search_call":
            self = .fileSearchCall(try FileSearchToolCall(from: decoder))
        case "function_call":
            self = .functionCall(try FunctionToolCall(from: decoder))
        case "web_search_call":
            self = .webSearchCall(try WebSearchToolCall(from: decoder))
        case "computer_call":
            self = .computerCall(try ComputerToolCall(from: decoder))
        case "reasoning":
            self = .reasoning(try Reasoning(from: decoder))
        default:
            throw DecodingError.dataCorruptedError(forKey: .type, in: container, debugDescription: "Unknown output type: \(type)")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        switch self {
        case .message(let message):
            try container.encode("message", forKey: .type)
            try message.encode(to: encoder)
        case .fileSearchCall(let call):
            try container.encode("file_search_call", forKey: .type)
            try call.encode(to: encoder)
        case .functionCall(let call):
            try container.encode("function_call", forKey: .type)
            try call.encode(to: encoder)
        case .webSearchCall(let call):
            try container.encode("web_search_call", forKey: .type)
            try call.encode(to: encoder)
        case .computerCall(let call):
            try container.encode("computer_call", forKey: .type)
            try call.encode(to: encoder)
        case .reasoning(let reasoning):
            try container.encode("reasoning", forKey: .type)
            try reasoning.encode(to: encoder)
        }
    }

    private enum CodingKeys: String, CodingKey {
        case type
    }
}

/// An output message from the model.
public struct OutputMessage: Codable, Sendable {
    /// The content of the output message.
    public let content: [ContentItem]

	/// The unique ID of the output message.
	public let id: String

	/// The role of the output message. Always assistant.
	public let role: Role

    /// The status of the message input.
    public let status: ResponseStatus

	/// The type of the output message. Always message.
	public let type: Response.MessageItemType
}

/// The results of a file search tool call.
public struct FileSearchToolCall: Codable, Sendable {
    /// The unique ID of the file search tool call.
    public let id: String

    /// The queries used to search for files.
    public let queries: [String]

	/// The status of the file search tool call.
	public let status: Response.ToolCallStatus

	/// The type of the file search tool call. Always file_search_call.
	public let type: Response.FileSearchCallType

    /// The results of the file search tool call.
    public let results: [FileSearchResult]?
}

/// A result from a file search.
public struct FileSearchResult: Codable, Sendable {
    // Add properties based on API documentation when available
}

/// A tool call to run a function.
public struct FunctionToolCall: Codable, Sendable {
    /// A JSON string of the arguments to pass to the function.
    public let arguments: String

    /// The unique ID of the function tool call generated by the model.
    public let callId: String

    /// The name of the function to run.
    public let name: String

	/// The type of the function tool call. Always function_call.
	public let type: Response.FunctionCallType

    /// The unique ID of the function tool call.
    public let id: String

    /// The status of the item.
    public let status: ResponseStatus
}

/// The results of a web search tool call.
public struct WebSearchToolCall: Codable, Sendable {
    /// The unique ID of the web search tool call.
    public let id: String

	/// The status of the web search tool call.
	public let status: Response.ToolCallStatus

	/// The type of the web search tool call. Always web_search_call.
	public let type: Response.WebSearchCallType

    // Add other properties based on API documentation when available
}

/// A tool call to a computer use tool.
public struct ComputerToolCall: Codable, Sendable {
    /// The action to perform.
    public let action: ComputerAction

    /// An identifier used when responding to the tool call with output.
    public let callId: String

    /// The unique ID of the computer call.
    public let id: String

    /// The pending safety checks for the computer call.
    public let pendingSafetyChecks: [String]

    /// The status of the item.
    public let status: ResponseStatus

	/// The type of the computer call. Always computer_call.
	public let type: Response.ComputerCallType
}

/// An action for a computer tool call.
public struct ComputerAction: Codable, Sendable {
    // Add properties based on API documentation when available
}
