//
//  Response.swift
//  SwiftAgents
//
//  Created by Oliver Drobnik on 24.04.25.
//

import Foundation
import SwiftMCP

/// Represents a response from the OpenAI API.
public struct Response: Codable, Sendable {
    /// Unique identifier for this Response.
    public let id: String

    /// The object type of this resource - always set to "response".
    public var object: String = "response"

    /// Unix timestamp (in seconds) of when this Response was created.
    public let createdAt: Date

    /// Unix timestamp (in seconds) of when this Response completed.
    public let completedAt: Date?

    /// The status of the response generation.
    public let status: ResponseStatus

    /// Whether this response is running in the background.
    public let background: Bool?

    /// An error object returned when the model fails to generate a Response.
    public let error: ErrorDetail?

    /// Details about why the response is incomplete.
    public let incompleteDetails: IncompleteDetails?

    /// Inserts a system (or developer) message as the first item in the model's context.
    public let instructions: String?

    /// An upper bound for the number of tokens that can be generated for a response.
    public let maxOutputTokens: Int?

    /// The maximum number of total calls to built-in tools that can be processed in a response.
    public let maxToolCalls: Int?

    /// Model ID used to generate the response.
    public let model: String

    /// An array of content items generated by the model.
    public let output: [OutputItem]

    /// SDK-only aggregated text output from all output_text items.
    public let outputText: String?

    /// Whether to allow the model to run tool calls in parallel.
    public let parallelToolCalls: Bool?

    /// The unique ID of the previous response to the model.
    public let previousResponseId: String?

    /// Configuration options for reasoning models (o-series models only).
    public let reasoning: Reasoning?

    /// What sampling temperature to use, between 0 and 2.
    public let temperature: Double?

    /// Configuration options for a text response from the model.
    public let text: TextConfiguration

    /// How the model should select which tool (or tools) to use.
    public let toolChoice: ToolChoice

    /// An array of tools the model may call while generating a response.
    public let tools: [ToolDescription]

    /// An alternative to sampling with temperature, called nucleus sampling.
    public var topP: Double?

    /// The truncation strategy to use for the model response.
    public let truncation: TruncationStrategy?

    /// Represents token usage details.
    public let usage: ResponsesUsage?

    /// A unique identifier representing your end-user.
    public let user: String?

    /// Set of key-value pairs that can be attached to an object.
    public let metadata: [String: String]?

    /// The service tier used to process the request.
    /// When not set, the default behavior is 'auto'.
    public let serviceTier: ServiceTier?

    /// The conversation that this response belongs to.
    public let conversation: Conversation?

    /// Reference to a prompt template and its variables.
    public let prompt: Prompt?

    /// Used by OpenAI to improve prompt cache hit rates.
    public let promptCacheKey: String?

    /// The retention policy for the prompt cache.
    public let promptCacheRetention: PromptCacheRetention?

    /// Stable identifier used for OpenAI safety systems.
    public let safetyIdentifier: String?

    /// Context management configuration for a response request.
    public struct ContextManagement: Codable, Sendable {
        /// The type of context management entry. Currently only compaction is supported.
        public let type: EntryType

        /// Token threshold at which compaction should trigger.
        public let compactThreshold: Int?

        public init(type: EntryType = .compaction, compactThreshold: Int? = nil) {
            self.type = type
            self.compactThreshold = compactThreshold
        }
    }

    /// Supported context management entry types.
    public enum EntryType: String, Codable, Sendable {
        case compaction
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case object
        case createdAt
        case completedAt
        case status
        case background
        case error
        case incompleteDetails
        case instructions
        case maxOutputTokens
        case maxToolCalls
        case model
        case output
        case outputText
        case parallelToolCalls
        case previousResponseId
        case reasoning
        case temperature
        case text
        case toolChoice
        case tools
        case topP
        case truncation
        case usage
        case user
        case metadata
        case serviceTier
        case conversation
        case prompt
        case promptCacheKey
        case promptCacheRetention
        case safetyIdentifier
    }

    public init(
        id: String,
        createdAt: Date,
        completedAt: Date? = nil,
        status: ResponseStatus,
        background: Bool? = nil,
        error: ErrorDetail?,
        incompleteDetails: IncompleteDetails?,
        instructions: String?,
        maxOutputTokens: Int?,
        maxToolCalls: Int? = nil,
        model: String,
        output: [OutputItem],
        outputText: String? = nil,
        parallelToolCalls: Bool?,
        previousResponseId: String?,
        reasoning: Reasoning?,
        temperature: Double?,
        text: TextConfiguration,
        toolChoice: ToolChoice,
        tools: [ToolDescription],
        topP: Double?,
        truncation: TruncationStrategy?,
        usage: ResponsesUsage?,
        user: String?,
        metadata: [String: String]?,
        serviceTier: ServiceTier? = .auto,
        conversation: Conversation? = nil,
        prompt: Prompt? = nil,
        promptCacheKey: String? = nil,
        promptCacheRetention: PromptCacheRetention? = nil,
        safetyIdentifier: String? = nil
    ) {
        self.id = id
        self.createdAt = createdAt
        self.completedAt = completedAt
        self.status = status
        self.background = background
        self.error = error
        self.incompleteDetails = incompleteDetails
        self.instructions = instructions
        self.maxOutputTokens = maxOutputTokens
        self.maxToolCalls = maxToolCalls
        self.model = model
        self.output = output
        self.outputText = outputText
        self.parallelToolCalls = parallelToolCalls
        self.previousResponseId = previousResponseId
        self.reasoning = reasoning
        self.temperature = temperature
        self.text = text
        self.toolChoice = toolChoice
        self.tools = tools
        self.topP = topP
        self.truncation = truncation
        self.usage = usage
        self.user = user
        self.metadata = metadata
        self.serviceTier = serviceTier
        self.conversation = conversation
        self.prompt = prompt
        self.promptCacheKey = promptCacheKey
        self.promptCacheRetention = promptCacheRetention
        self.safetyIdentifier = safetyIdentifier
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(String.self, forKey: .id)
        object = try container.decodeIfPresent(String.self, forKey: .object) ?? "response"
        createdAt = try container.decode(Date.self, forKey: .createdAt)
        completedAt = try container.decodeIfPresent(Date.self, forKey: .completedAt)
        status = try container.decode(ResponseStatus.self, forKey: .status)
        background = try container.decodeIfPresent(Bool.self, forKey: .background)
        error = try container.decodeIfPresent(ErrorDetail.self, forKey: .error)
        incompleteDetails = try container.decodeIfPresent(IncompleteDetails.self, forKey: .incompleteDetails)
        instructions = try container.decodeIfPresent(String.self, forKey: .instructions)
        maxOutputTokens = try container.decodeIfPresent(Int.self, forKey: .maxOutputTokens)
        maxToolCalls = try container.decodeIfPresent(Int.self, forKey: .maxToolCalls)
        model = try container.decode(String.self, forKey: .model)
        output = try container.decode([OutputItem].self, forKey: .output)
        outputText = try container.decodeIfPresent(String.self, forKey: .outputText)
        parallelToolCalls = try container.decodeIfPresent(Bool.self, forKey: .parallelToolCalls)
        previousResponseId = try container.decodeIfPresent(String.self, forKey: .previousResponseId)
        reasoning = try container.decodeIfPresent(Reasoning.self, forKey: .reasoning)
        temperature = try container.decodeIfPresent(Double.self, forKey: .temperature)
        text = try container.decode(TextConfiguration.self, forKey: .text)
        toolChoice = try container.decode(ToolChoice.self, forKey: .toolChoice)
        tools = try container.decode([ToolDescription].self, forKey: .tools)
        // LM Studio may send bool instead of Double for topP
        topP = try? container.decodeIfPresent(Double.self, forKey: .topP)
        truncation = try container.decodeIfPresent(TruncationStrategy.self, forKey: .truncation)
        usage = try container.decodeIfPresent(ResponsesUsage.self, forKey: .usage)
        user = try container.decodeIfPresent(String.self, forKey: .user)
        metadata = try container.decodeIfPresent([String: String].self, forKey: .metadata)
        serviceTier = try container.decodeIfPresent(ServiceTier.self, forKey: .serviceTier)
        conversation = try container.decodeIfPresent(Conversation.self, forKey: .conversation)
        prompt = try container.decodeIfPresent(Prompt.self, forKey: .prompt)
        promptCacheKey = try container.decodeIfPresent(String.self, forKey: .promptCacheKey)
        promptCacheRetention = try container.decodeIfPresent(PromptCacheRetention.self, forKey: .promptCacheRetention)
        safetyIdentifier = try container.decodeIfPresent(String.self, forKey: .safetyIdentifier)
    }
}

public extension Response {
    enum ListObjectType: String, Codable, Sendable {
        case list
    }

    enum Phase: String, Codable, Sendable {
        case commentary
        case finalAnswer = "final_answer"
    }

    enum MessageItemType: String, Codable, Sendable {
        case message
    }

    enum FileSearchCallType: String, Codable, Sendable {
        case fileSearchCall = "file_search_call"
    }

    enum FunctionCallType: String, Codable, Sendable {
        case functionCall = "function_call"
    }

    enum FunctionCallOutputType: String, Codable, Sendable {
        case functionCallOutput = "function_call_output"
    }

    enum WebSearchCallType: String, Codable, Sendable {
        case webSearchCall = "web_search_call"
    }

    enum ComputerCallType: String, Codable, Sendable {
        case computerCall = "computer_call"
    }

    enum ComputerCallOutputType: String, Codable, Sendable {
        case computerCallOutput = "computer_call_output"
    }

    enum ComputerScreenshotType: String, Codable, Sendable {
        case computerScreenshot = "computer_screenshot"
    }

    enum ItemReferenceType: String, Codable, Sendable {
        case itemReference = "item_reference"
    }

    enum ApplyPatchCallOutputType: String, Codable, Sendable {
        case applyPatchCallOutput = "apply_patch_call_output"
    }

    enum ToolCallStatus: String, Codable, Sendable {
        case inProgress = "in_progress"
        case searching
        case completed
        case incomplete
        case interpreting
        case calling
        case failed
    }

    enum ApplyPatchResultStatus: String, Codable, Sendable {
        case completed
        case failed
    }

    enum PromptCacheRetention: String, Codable, Sendable {
        // OpenAI's documented value is `in-memory` (with a hyphen) but
        // the API has been observed in the wild emitting the underscore
        // spelling `in_memory`. Accept both so a future-tense rename
        // doesn't break the decode path.
        case inMemory = "in-memory"
        case inMemoryUnderscore = "in_memory"
        case retention24h = "24h"
    }

    struct Conversation: Codable, Sendable {
        public let id: String
    }

    struct Prompt: Codable, Sendable {
        public let id: String
        public let variables: [String: JSONValue]?
        public let version: String?

        public init(id: String, variables: [String: JSONValue]? = nil, version: String? = nil) {
            self.id = id
            self.variables = variables
            self.version = version
        }
    }
}
