extension ResponseOutput {
    /// A tool call to run a function.
    public struct FunctionToolCall: Codable, Sendable {
        /// A JSON string of the arguments to pass to the function.
        public let arguments: String

        /// The unique ID of the function tool call generated by the model.
        public let callId: String

        /// The name of the function to run.
        public let name: String

        /// The type of the function tool call. Always function_call.
        public let type: Response.FunctionCallType

        /// The unique ID of the function tool call.
        public let id: String

        /// The status of the item.
        public let status: ResponseStatus
    }
}
