//
//  LocalVectorStore.swift
//  SwiftAgents
//
//  Created by Oliver Drobnik on 16.04.24.
//

import Foundation
import Providers

struct TextFragment {
    var text: String
    var source: String
    var similarity: Double
}

struct TextChunk {
    let text: String
    let embedding: Vector
    let embeddingModel: String
    let source: String
}

struct TextSource {
    let name: String
    let embedding: Vector
}

/// Stores text chunks with their embedding vector generated by the `embeddingProvider`
class LocalVectorStore {
    private var chunks = [TextChunk]()

    /// The EmbeddingProvider to use for getting vector embeddings for indexing and searching, defaults to local
    /// NLContextEmbedding
    let embeddingProvider: EmbeddingProvider

    init(embeddingProvider: EmbeddingProvider? = nil) {
        self.embeddingProvider = embeddingProvider ?? ContextualEmbeddingProvider()
    }

    func indexText(_ text: String, source: String) async throws {
        let chunker = TextChunker(text: text)

        var tmpArray = [TextChunk]()

        for section in chunker.sections {
            guard let embedding = try await embeddingProvider.embedding(for: section) else {
                continue
            }

            let chunk = TextChunk(
                text: section,
                embedding: embedding,
                embeddingModel: embeddingProvider.embeddingModelIdentifier,
                source: source
            )

            tmpArray.append(chunk)
        }

        chunks.append(contentsOf: tmpArray)
    }

    func search(text: String, topN: Int) async throws -> [TextFragment] {
        guard let queryVector = try await embeddingProvider.embedding(for: text) else {
            return []
        }

        var results = [TextFragment]()

        for chunk in chunks {
            let similarity = chunk.embedding.cosineSimilarityForUnitVector(to: queryVector)

            if similarity > 0 { // Consider only positive similarities

                let fragment = TextFragment(text: chunk.text, source: chunk.source, similarity: similarity)
                results.append(fragment)
            }
        }

        // Sort results by similarity in descending order and return the top N results
        return results.sorted { $0.similarity > $1.similarity }.prefix(topN).map { $0 }
    }
}
