//
//  LocalVectorStore.swift
//  SwiftAgents
//
//  Created by Oliver Drobnik on 16.04.24.
//

import Foundation
import Providers

struct TextFragment {
    var text: String
    var source: String
    var similarity: Double
}

struct TextChunk {
    let text: String
    let embedding: Vector
    let embeddingModel: String
    let source: String
}

struct TextSource {
    let name: String
    let embedding: Vector
}

/// Stores text chunks with their embedding vector generated by the `embeddingProvider`
class LocalVectorStore {
    private var chunks = [TextChunk]()

    /// The EmbeddingProvider to use for getting vector embeddings for indexing and searching, defaults to local
    /// NLContextEmbedding
    let embeddingProvider: EmbeddingProvider

    init(embeddingProvider: EmbeddingProvider? = nil) {
        #if canImport(NaturalLanguage)
        self.embeddingProvider = embeddingProvider ?? ContextualEmbeddingProvider()
        #else
        // `ContextualEmbeddingProvider` and `TextChunker` are
        // `NaturalLanguage`-backed and only exist on Apple platforms.
        // On Linux callers must supply an explicit provider (typically
        // `OpenAI` or `OllamaAPI` as the embedding source).
        guard let embeddingProvider else {
            preconditionFailure(
                "LocalVectorStore requires an explicit embeddingProvider on platforms without NaturalLanguage."
            )
        }
        self.embeddingProvider = embeddingProvider
        #endif
    }

    func indexText(_ text: String, source: String) async throws {
        #if canImport(NaturalLanguage)
        // `TextChunker.sections` is an IUO (`[String]!`); pin the type
        // here so the for-loop sees a plain `[String]`.
        let sections: [String] = TextChunker(text: text).sections
        #else
        // Linux / non-Apple: skip `NLLanguageRecognizer`-based chunking
        // and treat the whole input as a single section. Consumers that
        // need real chunking on Linux should pre-split their input.
        let sections = [text]
        #endif

        var tmpArray = [TextChunk]()

        for section in sections {
            guard let embedding = try await embeddingProvider.embedding(for: section, role: .document) else {
                continue
            }

            let chunk = TextChunk(
                text: section,
                embedding: embedding,
                embeddingModel: embeddingProvider.embeddingModelIdentifier,
                source: source
            )

            tmpArray.append(chunk)
        }

        chunks.append(contentsOf: tmpArray)
    }

    func search(text: String, topN: Int) async throws -> [TextFragment] {
        guard let queryVector = try await embeddingProvider.embedding(for: text, role: .query) else {
            return []
        }

        var results = [TextFragment]()

        for chunk in chunks {
            let similarity = chunk.embedding.cosineSimilarityForUnitVector(to: queryVector)

            if similarity > 0 { // Consider only positive similarities

                let fragment = TextFragment(text: chunk.text, source: chunk.source, similarity: similarity)
                results.append(fragment)
            }
        }

        // Sort results by similarity in descending order and return the top N results
        return results.sorted { $0.similarity > $1.similarity }.prefix(topN).map { $0 }
    }
}
